package threeproxy

import "testing"

// Vectors generated by running the actual upstream 3proxy_crypt utility
// (compiled from 3proxy master, September 2026). If these break, the
// hash implementation drifted and users would be unable to authenticate
// against the engine — this is a release-blocking regression test.
func TestCRHashMatchesUpstreamVectors(t *testing.T) {
	vectors := []struct {
		salt, password, want string
	}{
		{"testsalt", "hunter2-password", "$3$testsalt$6/A9E8lvI/V3WZcOHwGL71"},
		{"s1", "p", "$3$s1$r3LV1UwVOESoo9mQu0tUc."},
		{"abcdefghijklmnopqrstuvwxyz0123456789", "correct-staple-9x", "$3$abcdefghijklmnopqrstuvwxyz0123456789$oUqnrUyusM6TDUdw7eMtU/"},
	}
	for _, v := range vectors {
		if got := CRHash(v.password, v.salt); got != v.want {
			t.Errorf("CRHash(%q, %q) = %q, want %q", v.password, v.salt, got, v.want)
		}
	}
}

func TestCRHashProperties(t *testing.T) {
	// Same password, different salt -> different verifier.
	a, _ := NewEngineHash("same-password-1")
	b, _ := NewEngineHash("same-password-1")
	if a == b {
		t.Fatal("two salts produced identical verifiers")
	}
	// Salted hash does not contain the password.
	if got := CRHash("secret-password-value", "salt"); got == "secret-password-value" {
		t.Fatal("hash equals password")
	}
	// Deterministic: same inputs, same output.
	if CRHash("pw", "salt") != CRHash("pw", "salt") {
		t.Fatal("hash not deterministic")
	}
}

func TestNewSalt(t *testing.T) {
	for i := 0; i < 100; i++ {
		s, err := NewSalt()
		if err != nil {
			t.Fatal(err)
		}
		if len(s) != 16 {
			t.Fatalf("salt length = %d, want 16", len(s))
		}
		for j := 0; j < len(s); j++ {
			c := s[j]
			ok := (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9')
			if !ok {
				t.Fatalf("salt %q contains config-significant byte %q", s, string(rune(c)))
			}
		}
	}
}
