// Package users implements proxy-user management: the service layer shared
// by the HTTP API and the admin CLI. It owns the credential lifecycle —
// passwords exist in plaintext only inside a Create/Rotate call and are
// returned to the caller exactly once — and derives the desired data-plane
// state (engine.State) from persisted users.
//
// Security invariants enforced here (not in any UI):
//   - usernames pass engine.ValidateUsername before anything is stored
//     (the engine-config injection defense, docs/SECURITY-TESTING.md §6);
//   - no method ever returns a hash, and only Create/Rotate return the
//     plaintext password;
//   - every mutation is audited, and audit details never contain
//     credentials or rejected input.
package users

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strconv"
	"sort"
	"strings"
	"time"

	"github.com/xoxproxy/xoxproxy/internal/audit"
	"github.com/xoxproxy/xoxproxy/internal/auth"
	"github.com/xoxproxy/xoxproxy/internal/engine"
	"github.com/xoxproxy/xoxproxy/internal/engine/threeproxy"
	"github.com/xoxproxy/xoxproxy/internal/store"
)

// Sentinel errors. Handlers map them to status codes; nothing internal
// ever crosses the API boundary.
var (
	// ErrInvalidInput covers every validation failure; the wrapped message
	// is safe for API responses.
	ErrInvalidInput    = errors.New("invalid input")
	ErrUsernameTaken   = errors.New("username already taken")
	ErrVersionConflict = errors.New("user was modified concurrently")
	ErrWeakPassword    = errors.New("password does not meet policy")
	// ErrExpired is returned when enabling a user whose expiry has passed:
	// re-enabling without extending the expiry would be a silent no-op.
	ErrExpired = errors.New("user's expiry has passed; extend expires_at first")
)

// Proxy-user password policy. Deliberately lighter than the admin policy:
// these credentials are machine-generated by default and grant proxy
// access, not control-plane access.
const (
	MinProxyPasswordLength = 8
	MaxProxyPasswordLength = 256
)

// validProtocols is the closed protocol vocabulary; anything else is
// rejected before storage.
var validProtocols = map[string]bool{"http": true, "socks5": true}

// Actor identifies who performed an operation, for the audit trail.
type Actor struct {
	Name      string // admin username or "cli"
	RequestID string
	SourceIP  string
	UserAgent string
}

// UsageResetter zeroes a user's current quota window in the usage ledger
// (the control plane's authoritative accounting record). The analytics
// repository satisfies it; the seam keeps the users package independent
// of the analytics pipeline.
type UsageResetter interface {
	ResetUsage(ctx context.Context, userID int64, day, month string) (int64, error)
}

// Service is the proxy-user service layer.
type Service struct {
	users  store.UserRepository
	creds  store.CredentialRepository
	audit  *audit.Service
	logger *slog.Logger

	// onChange is invoked after any successful mutation that can change
	// the derived engine state (the deploy pipeline's trigger). Set once
	// during wiring, before traffic; nil (CLI/test) means no-op.
	onChange StateChangeHook

	// usageResetter zeroes the usage ledger on quota reset; nil (tests,
	// reduced deployments) makes ResetQuota a ledger no-op that still
	// audits and reports.
	usageResetter UsageResetter

	// Credential primitives are fields so tests can pin entropy; the
	// defaults are the only approved production sources.
	newEngineHash    func(password string) (string, error)
	newAPIHash       func(password string) (string, error)
	generatePassword func() string
	now              func() time.Time
}

// StateChangeHook is notified after a successful mutation. actor is the
// audit actor ("admin", "cli", "system"); reason names the change with a
// fixed vocabulary, e.g. "user.create:alice" (target usernames are
// charset-validated, never raw request input).
type StateChangeHook func(actor, reason string)

// SetStateChangeHook registers the deploy trigger. Call exactly once
// during wiring, before the service handles any traffic.
func (s *Service) SetStateChangeHook(h StateChangeHook) { s.onChange = h }

// SetUsageResetter registers the usage-ledger reset seam for quota
// resets. Optional: without it ResetQuota audits and succeeds but does
// not touch the ledger.
func (s *Service) SetUsageResetter(r UsageResetter) { s.usageResetter = r }

func (s *Service) notify(actor, reason string) {
	if s.onChange != nil {
		s.onChange(actor, reason)
	}
}

// NewService builds the service. The repositories must share one database
// handle so cross-table operations stay transactional.
func NewService(logger *slog.Logger, users store.UserRepository, creds store.CredentialRepository, auditSvc *audit.Service) *Service {
	return &Service{
		users:            users,
		creds:            creds,
		audit:            auditSvc,
		logger:           logger,
		newEngineHash:    threeproxy.NewEngineHash,
		newAPIHash:       auth.HashPassword,
		generatePassword: auth.GeneratePassword,
		now:              time.Now,
	}
}

// --- inputs ---

// CreateInput describes a new proxy user. Password is optional; empty
// means "generate one".
type CreateInput struct {
	Username          string
	Password          string
	Protocols         []string
	DownloadBPS       int64
	UploadBPS         int64
	MaxConnections    int64
	QuotaBytesDaily   int64
	QuotaBytesMonthly int64
	ExpiresAt         *time.Time
}

// UpdateInput is a partial update. Nil pointers mean "leave unchanged";
// ClearExpiration distinguishes "no change" from "set to never".
type UpdateInput struct {
	Version           int64 // required: optimistic-lock token
	Protocols         *[]string
	DownloadBPS       *int64
	UploadBPS         *int64
	MaxConnections    *int64
	QuotaBytesDaily   *int64
	QuotaBytesMonthly *int64
	ExpiresAt         *time.Time
	ClearExpiration   bool
}

// --- lifecycle ---

// Create validates and persists a new user with its first credential. The
// returned string is the one-time plaintext password (generated when the
// input left Password empty).
func (s *Service) Create(ctx context.Context, in CreateInput, actor Actor) (store.ProxyUser, string, error) {
	if err := s.validateNew(&in); err != nil {
		return store.ProxyUser{}, "", err
	}

	password := in.Password
	if password == "" {
		password = s.generatePassword()
	}
	engineHash, err := s.newEngineHash(password)
	if err != nil {
		return store.ProxyUser{}, "", fmt.Errorf("users: engine hash: %w", err)
	}
	apiHash, err := s.newAPIHash(password)
	if err != nil {
		return store.ProxyUser{}, "", fmt.Errorf("users: api hash: %w", err)
	}

	now := s.now().UTC()
	created, err := s.users.CreateUser(ctx, store.ProxyUser{
		ServerID:          "local",
		Username:          in.Username,
		Status:            store.UserActive,
		AllowedProtocols:  in.Protocols,
		DownloadBPS:       in.DownloadBPS,
		UploadBPS:         in.UploadBPS,
		MaxConnections:    in.MaxConnections,
		QuotaBytesDaily:   in.QuotaBytesDaily,
		QuotaBytesMonthly: in.QuotaBytesMonthly,
		ExpiresAt:         in.ExpiresAt,
		CreatedAt:         now,
		UpdatedAt:         now,
	}, store.Credential{
		EngineHash: engineHash,
		APIHash:    apiHash,
		Status:     store.CredentialActive,
		CreatedAt:  now,
	})
	if err != nil {
		if errors.Is(err, store.ErrConflict) {
			s.auditAction(ctx, actor, "user.create", in.Username, "failure", "username taken")
			return store.ProxyUser{}, "", fmt.Errorf("%w: %s", ErrUsernameTaken, in.Username)
		}
		return store.ProxyUser{}, "", err
	}
	s.auditAction(ctx, actor, "user.create", in.Username, "success", "")
	s.notify(actor.Name, "user.create:"+in.Username)
	return created, password, nil
}

// Get returns one user.
func (s *Service) Get(ctx context.Context, id int64) (store.ProxyUser, error) {
	return s.users.GetUserByID(ctx, id)
}

// List returns users matching the filter.
func (s *Service) List(ctx context.Context, f store.UserFilter) ([]store.ProxyUser, error) {
	return s.users.ListUsers(ctx, f)
}

// Update applies a partial update under optimistic locking. The version in
// the input must match the stored row; otherwise ErrVersionConflict.
func (s *Service) Update(ctx context.Context, id int64, in UpdateInput, actor Actor) (store.ProxyUser, error) {
	current, err := s.users.GetUserByID(ctx, id)
	if err != nil {
		return store.ProxyUser{}, err
	}
	if in.Version == 0 || in.Version != current.Version {
		return store.ProxyUser{}, fmt.Errorf("%w: have version %d, request carries %d", ErrVersionConflict, current.Version, in.Version)
	}

	next := current
	if in.Protocols != nil {
		next.AllowedProtocols = *in.Protocols
	}
	if in.DownloadBPS != nil {
		next.DownloadBPS = *in.DownloadBPS
	}
	if in.UploadBPS != nil {
		next.UploadBPS = *in.UploadBPS
	}
	if in.MaxConnections != nil {
		next.MaxConnections = *in.MaxConnections
	}
	if in.QuotaBytesDaily != nil {
		next.QuotaBytesDaily = *in.QuotaBytesDaily
	}
	if in.QuotaBytesMonthly != nil {
		next.QuotaBytesMonthly = *in.QuotaBytesMonthly
	}
	switch {
	case in.ClearExpiration:
		next.ExpiresAt = nil
	case in.ExpiresAt != nil:
		next.ExpiresAt = in.ExpiresAt
	}

	if err := s.validateMutated(&next); err != nil {
		return store.ProxyUser{}, err
	}

	updated, err := s.users.UpdateUser(ctx, next)
	if err != nil {
		if errors.Is(err, store.ErrConflict) {
			s.auditAction(ctx, actor, "user.update", current.Username, "failure", "version conflict")
			return store.ProxyUser{}, ErrVersionConflict
		}
		return store.ProxyUser{}, err
	}
	s.auditAction(ctx, actor, "user.update", current.Username, "success", updateSummary(current, updated))
	s.notify(actor.Name, "user.update:"+current.Username)
	return updated, nil
}

// Delete removes a user and its credentials permanently.
func (s *Service) Delete(ctx context.Context, id int64, actor Actor) error {
	current, err := s.users.GetUserByID(ctx, id)
	if err != nil {
		return err
	}
	if err := s.users.DeleteUser(ctx, id); err != nil {
		return err
	}
	s.auditAction(ctx, actor, "user.delete", current.Username, "success", "")
	s.notify(actor.Name, "user.delete:"+current.Username)
	return nil
}

// RotateCredentials replaces the active password with a new one (generated
// unless password is given) and revokes the old credential atomically.
// Live connections re-authenticate at their next I/O after the resulting
// config deployment, so rotation takes effect without killing sessions
// wholesale (docs/SPIKE-3PROXY.md §1).
func (s *Service) RotateCredentials(ctx context.Context, id int64, password string, actor Actor) (store.ProxyUser, string, error) {
	current, err := s.users.GetUserByID(ctx, id)
	if err != nil {
		return store.ProxyUser{}, "", err
	}
	if password == "" {
		password = s.generatePassword()
	} else if err := s.validatePassword(password, current.Username); err != nil {
		return store.ProxyUser{}, "", err
	}

	engineHash, err := s.newEngineHash(password)
	if err != nil {
		return store.ProxyUser{}, "", fmt.Errorf("users: engine hash: %w", err)
	}
	apiHash, err := s.newAPIHash(password)
	if err != nil {
		return store.ProxyUser{}, "", fmt.Errorf("users: api hash: %w", err)
	}

	updated, err := s.creds.RotateCredential(ctx, id, store.Credential{
		EngineHash: engineHash,
		APIHash:    apiHash,
		Status:     store.CredentialActive,
		CreatedAt:  s.now().UTC(),
	}, current.Version, s.now().UTC())
	if err != nil {
		if errors.Is(err, store.ErrConflict) {
			s.auditAction(ctx, actor, "user.rotate_credentials", current.Username, "failure", "version conflict")
			return store.ProxyUser{}, "", ErrVersionConflict
		}
		return store.ProxyUser{}, "", err
	}
	s.auditAction(ctx, actor, "user.rotate_credentials", current.Username, "success", "")
	s.notify(actor.Name, "user.rotate_credentials:"+current.Username)
	return updated, password, nil
}

// Disable withdraws access (any status → disabled).
func (s *Service) Disable(ctx context.Context, id int64, expectedVersion int64, actor Actor) (store.ProxyUser, error) {
	return s.transition(ctx, id, store.UserDisabled, expectedVersion, actor, "user.disable")
}

// Enable restores access. A user whose expiry has passed cannot be enabled
// without first extending the expiry — otherwise the call would appear to
// succeed while the desired-state builder still excludes the user.
func (s *Service) Enable(ctx context.Context, id int64, expectedVersion int64, actor Actor) (store.ProxyUser, error) {
	current, err := s.users.GetUserByID(ctx, id)
	if err != nil {
		return store.ProxyUser{}, err
	}
	if current.ExpiresAt != nil && !current.ExpiresAt.After(s.now()) {
		return store.ProxyUser{}, ErrExpired
	}
	return s.transition(ctx, id, store.UserActive, expectedVersion, actor, "user.enable")
}

func (s *Service) transition(ctx context.Context, id int64, status string, expectedVersion int64, actor Actor, action string) (store.ProxyUser, error) {
	current, err := s.users.GetUserByID(ctx, id)
	if err != nil {
		return store.ProxyUser{}, err
	}
	updated, err := s.users.SetUserStatus(ctx, id, status, expectedVersion, s.now().UTC())
	if err != nil {
		if errors.Is(err, store.ErrConflict) {
			s.auditAction(ctx, actor, action, current.Username, "failure", "version conflict")
			return store.ProxyUser{}, ErrVersionConflict
		}
		return store.ProxyUser{}, err
	}
	s.auditAction(ctx, actor, action, current.Username, "success", "")
	s.notify(actor.Name, action+":"+current.Username)
	return updated, nil
}

// ResetQuota zeroes a user's usage for the current quota window in the
// control-plane ledger. The engine's own counter (the enforcement
// mechanism) is unaffected — this is the dashboard/billing record, not a
// grant of more traffic; quota enforcement semantics live in the data
// plane (docs/SPIKE-3PROXY.md §2).
func (s *Service) ResetQuota(ctx context.Context, id int64, actor Actor) (store.ProxyUser, error) {
	current, err := s.users.GetUserByID(ctx, id)
	if err != nil {
		return store.ProxyUser{}, err
	}

	now := s.now().UTC()
	day := now.Format("2006-01-02")
	month := now.Format("2006-01")
	var rows int64
	if s.usageResetter != nil {
		rows, err = s.usageResetter.ResetUsage(ctx, id, day, month)
		if err != nil {
			return store.ProxyUser{}, err
		}
	}
	s.auditAction(ctx, actor, "user.reset_quota", current.Username, "success",
		strconv.FormatInt(rows, 10)+" ledger rows")
	// No engine-state change: quotas render from the config unchanged, so
	// no deploy trigger. The notify vocabulary stays reserved for changes
	// the deploy pipeline must observe.
	return current, nil
}

// SweepExpired is the expiration reconciliation pass (GUIDE: expiry must
// not depend on the dashboard being open). It is safe to run concurrently
// with everything else: the transition is a single idempotent UPDATE.
func (s *Service) SweepExpired(ctx context.Context) (int64, error) {
	n, err := s.users.SweepExpired(ctx, s.now().UTC())
	if err != nil {
		return 0, err
	}
	if n > 0 {
		s.auditAction(ctx, Actor{Name: "system"}, "user.expire_sweep", "", "success",
			fmt.Sprintf("expired %d user(s)", n))
		// Expired users must leave the engine config; a deploy is due.
		s.notify("system", "expiry-sweep")
	}
	return n, nil
}

// --- validation ---

func (s *Service) validateNew(in *CreateInput) error {
	var errs []error
	if err := engine.ValidateUsername(in.Username); err != nil {
		errs = append(errs, err)
	}
	errs = append(errs, validateProtocols(in.Protocols)...)
	errs = append(errs, validateLimits(
		in.DownloadBPS, in.UploadBPS, in.MaxConnections,
		in.QuotaBytesDaily, in.QuotaBytesMonthly)...)
	if in.ExpiresAt != nil && !in.ExpiresAt.After(s.now()) {
		errs = append(errs, fmt.Errorf("%w: expires_at must be in the future", ErrInvalidInput))
	}
	if in.Password != "" {
		if err := s.validatePassword(in.Password, in.Username); err != nil {
			errs = append(errs, err)
		}
	}
	return joinInputErrors(errs)
}

// validateMutated re-checks a merged user before it is written. Status and
// expiry are deliberately not re-validated here: extending an expiry
// backwards (into the past) is a legitimate correction, and the sweep plus
// the state builder both handle past expiry safely.
func (s *Service) validateMutated(u *store.ProxyUser) error {
	var errs []error
	errs = append(errs, validateProtocols(u.AllowedProtocols)...)
	errs = append(errs, validateLimits(
		u.DownloadBPS, u.UploadBPS, u.MaxConnections,
		u.QuotaBytesDaily, u.QuotaBytesMonthly)...)
	return joinInputErrors(errs)
}

// validateLimits checks every numeric field. Quotas must be either 0
// (unlimited) or at least the engine's 1 MiB enforcement granularity —
// anything in between would be silently rounded down by the data plane.
func validateLimits(downloadBPS, uploadBPS, maxConns, quotaDaily, quotaMonthly int64) []error {
	var errs []error
	for name, v := range map[string]int64{
		"download_limit_bps": downloadBPS,
		"upload_limit_bps":   uploadBPS,
		"max_connections":    maxConns,
	} {
		if v < 0 {
			errs = append(errs, fmt.Errorf("%w: %s must be >= 0", ErrInvalidInput, name))
		}
	}
	for name, v := range map[string]int64{
		"quota_bytes_daily":   quotaDaily,
		"quota_bytes_monthly": quotaMonthly,
	} {
		if v != 0 && v < engine.MiB {
			errs = append(errs, fmt.Errorf("%w: %s must be 0 (unlimited) or at least %d bytes", ErrInvalidInput, name, engine.MiB))
		}
	}
	return errs
}

func validateProtocols(protocols []string) []error {
	var errs []error
	if len(protocols) == 0 {
		return []error{fmt.Errorf("%w: at least one protocol (http, socks5) is required", ErrInvalidInput)}
	}
	seen := make(map[string]bool, len(protocols))
	for _, p := range protocols {
		if !validProtocols[p] {
			errs = append(errs, fmt.Errorf("%w: unknown protocol %q (allowed: http, socks5)", ErrInvalidInput, p))
		}
		if seen[p] {
			errs = append(errs, fmt.Errorf("%w: protocol %q listed more than once", ErrInvalidInput, p))
		}
		seen[p] = true
	}
	return errs
}

func (s *Service) validatePassword(password, username string) error {
	if len(password) < MinProxyPasswordLength {
		return fmt.Errorf("%w: must be at least %d characters", ErrWeakPassword, MinProxyPasswordLength)
	}
	if len(password) > MaxProxyPasswordLength {
		return fmt.Errorf("%w: must be at most %d characters", ErrWeakPassword, MaxProxyPasswordLength)
	}
	if username != "" && len(username) >= 3 && strings.Contains(strings.ToLower(password), strings.ToLower(username)) {
		return fmt.Errorf("%w: must not contain the username", ErrWeakPassword)
	}
	return nil
}

func joinInputErrors(errs []error) error {
	switch len(errs) {
	case 0:
		return nil
	case 1:
		return fmt.Errorf("%w: %s", ErrInvalidInput, errs[0].Error())
	default:
		msgs := make([]string, len(errs))
		for i, e := range errs {
			msgs[i] = e.Error()
		}
		return fmt.Errorf("%w: %s", ErrInvalidInput, strings.Join(msgs, "; "))
	}
}

// --- audit ---

// auditAction records a mutation. Failures are logged loudly but do not
// fail the business operation (consistent with the audit package policy);
// target is always a validated username, never raw request input.
func (s *Service) auditAction(ctx context.Context, actor Actor, action, target, result, detail string) {
	entry := store.AuditEntry{
		Actor:     actor.Name,
		Action:    action,
		Target:    target,
		RequestID: actor.RequestID,
		SourceIP:  actor.SourceIP,
		UserAgent: actor.UserAgent,
		Result:    result,
		Detail:    detail,
	}
	if err := s.audit.Record(ctx, entry); err != nil {
		s.logger.Error("user action audit failed",
			slog.String("action", action), slog.String("error", err.Error()))
	}
}

// updateSummary describes what changed, for the audit trail. Values are
// all numeric or validated strings — no secrets, no raw input.
func updateSummary(before, after store.ProxyUser) string {
	var parts []string
	if before.DownloadBPS != after.DownloadBPS {
		parts = append(parts, fmt.Sprintf("download %d->%d bps", before.DownloadBPS, after.DownloadBPS))
	}
	if before.UploadBPS != after.UploadBPS {
		parts = append(parts, fmt.Sprintf("upload %d->%d bps", before.UploadBPS, after.UploadBPS))
	}
	if before.MaxConnections != after.MaxConnections {
		parts = append(parts, fmt.Sprintf("max_connections %d->%d", before.MaxConnections, after.MaxConnections))
	}
	if before.QuotaBytesDaily != after.QuotaBytesDaily {
		parts = append(parts, fmt.Sprintf("daily quota %d->%d bytes", before.QuotaBytesDaily, after.QuotaBytesDaily))
	}
	if before.QuotaBytesMonthly != after.QuotaBytesMonthly {
		parts = append(parts, fmt.Sprintf("monthly quota %d->%d bytes", before.QuotaBytesMonthly, after.QuotaBytesMonthly))
	}
	if !sameProtocols(before.AllowedProtocols, after.AllowedProtocols) {
		parts = append(parts, fmt.Sprintf("protocols %v", after.AllowedProtocols))
	}
	if !sameTime(before.ExpiresAt, after.ExpiresAt) {
		parts = append(parts, "expiry changed")
	}
	if len(parts) == 0 {
		return "no field changes"
	}
	return strings.Join(parts, ", ")
}

func sameProtocols(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	ac, bc := append([]string(nil), a...), append([]string(nil), b...)
	sort.Strings(ac)
	sort.Strings(bc)
	for i := range ac {
		if ac[i] != bc[i] {
			return false
		}
	}
	return true
}

func sameTime(a, b *time.Time) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	return a.Equal(*b)
}
